theme: jekyll-theme-minimal
title: 'UC Davis Bioinformatics Prerequisites Workshop'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: welcome

  - heading: CLI Intro
  - title: Introduction and Getting Connected # MATT
    url: CLI_Intro/logging-in
  - title: Unix & the Command Line # KEITH
    url: CLI_Intro/command-line-intro
  - title: Unix & the Command Line - Challenge Solutions # KEITH
    url: CLI_Intro/command-line-intro-challenge-solutions
  - title: Some Bioinformatics File Formats # MATT
    url: CLI_Intro/formats.pdf
  - title: Installing Simple Bioinformatics Software & Conda # NIK
    url: CLI_Intro/software


  - heading: Advanced CLI
  - title: Clusters & Modules # KEITH
    url: Advanced_CLI/cluster
  - title: Git Basics # HANNAH
    url:
  - title: Folder and Experiment Structure # MATT
    url:
  - title: Advanced Command Line Topics # NIK
    url: Advanced_CLI/advanced-command-line
  - title: Advanced Challenge Solutions # NIK
    url: Advanced_CLI/advanced-challenge-solutions
  - title: A Simple RNA-Seq Workflow # NIK
    url: Advanced_CLI/bioworkflow


  - heading: Intro to R
  - title: Introduction to R
    url: Intro_to_R/Intro2R/Intro2R.html
  - title: Data in R - Prepare
    url: Intro_to_R/Intro2R/data_in_R_prepare_fixed
  - title: Data in R
    url: Intro_to_R/Intro2R/data_in_R_fixed


  - heading: Advanced R
  - title: R Oddities
    url: Advanced_R/R_Oddities.Rmd
  - title: Walkthrough of Vignettes for limma and biomaRt
    url: Advanced_R/limma_biomart_vignettes.Rmd
  - title: Linear Models in R
    url: Advanced_R/linear_models.Rmd


    # todo for Wed/Advanced_R:
      # stats talk = linear models in R?
      # R md  and notebooks
      # Data munging?
      # tidyverse, data frame manipulation
      # Figures in R and model building


  - heading: Optional
  - title: CLI Warmup / Review
    url: Advanced_CLI/warmup
  - title: CLI Warmup - Solutions
    url: Advanced_CLI/warmup-solution
  - title: Using Screen to Manage Multiple Projects
    url: Advanced_CLI/screen.pdf

  - heading: ETC
  - title: Examples of Markdown Formatting
    url: examples
  - title: Github
    url: https://github.com/ucdavis-bioinformatics-training/2019-Winter-Bioinformatics_Command_Line_and_R_Prerequisites_Workshop
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu

