theme: jekyll-theme-minimal
title: 'UC Davis Bioinformatics Prerequisites'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: welcome
  - title: Examples of Markdown Formatting
    url: examples


  - heading: CLI Intro
  - title: Introduction and Getting Connected # MATT
    url: monday/logging-in
  - title: Unix & the Command Line - HANDS-ON # KEITH
    url: monday/command-line-intro
  - title: Unix & the Command Line - Challenge Solutions - HANDS-ON # KEITH
    url: monday/command-line-intro-challenge-solutions
  - title: Some Bioinformatics File Formats - TALK # MATT
    url: monday/formats.pdf
  - title: Installing Simple Bioinformatics Software & Conda- HANDS-ON # NICK
    url: monday/software

  - heading: Advanced CLI
  - title: Clusters & Modules - HANDS-ON # KEITH
    url: tuesday/cluster
  - title: Git Basics # HANNAH
    url:
  - title: Folder and Experiment Structure # MATT
    url:
  - title: Advanced Command Line Topics - HANDS-ON # NICK
    url: tuesday/advanced-command-line
  - title: Advanced Challenge Solutions # NICK
    url: tuesday/advanced-challenge-solutions
  - title: A Simple RNA-Seq Workflow # NICK
    url: tuesday/bioworkflow


  - heading: Intro to R
  - title: Introduction to R
    url: wednesday/Intro2R/Intro2R_fixed
  - title: Data in R - Prepare
    url: wednesday/Intro2R/data_in_R_prepare_fixed
  - title: Data in R
    url: wednesday/Intro2R/data_in_R_fixed


  - heading: Advanced R
  - title: R Oddities
    url: thursday/
  - title: Walkthrough of Vignettes for limma and biomaRt
    url: wednesday/Data_in_R/data_in_R_prepare.md
  - title: Linear Models in R
    url: wednesday/Data_in_R/data_in_R.md


    # todo for Wed/Thursday:
      # stats talk = linear models in R?
      # R md  and notebooks
      # Data munging?
      # tidyverse, data frame manipulation
      # Figures in R and model building


  - heading: Optional
  - title: Warmup / Review - HANDS-ON
    url: tuesday/warmup
  - title: Warmup - Solutions - HANDS-ON
    url: tuesday/warmup-solution
  - title: Using Screen to Manage Multiple Projects - TALK
    url: tuesday/screen.pdf