theme: jekyll-theme-minimal
title: 'UC Davis Bioinformatics Prerequisites Workshop'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: welcome
  - title: Getting Connected # MATT
    url: CLI_Intro/logging-in
  - title: What is Bioinformatics/Genomics Perspective?
    url: pdfs/Genomics_a_perspective_Sept2_2019.pdf

  - heading: CLI Intro
  - title: Unix & the Command Line # KEITH
    url: CLI_Intro/command-line-intro
    #TODO add more info on when not to uncompress files
  - title: Unix & the Command Line - Challenge Solutions # KEITH
    url: CLI_Intro/command-line-intro-challenge-solutions
#  - title: Some Bioinformatics File Formats # MATT
#    url: CLI_Intro/formats.pdf
  - title: Environment Variables
    url: CLI_Intro/env
  - title: Installing Simple Bioinformatics Software # NIK
    url: CLI_Intro/software
  - title: Conda
    url: CLI_Intro/conda
  - title: Clusters & Modules # KEITH
    url: CLI_Intro/cluster


  - heading: Advanced CLI
  - title: Git Basics # HANNAH
    url: Advanced_CLI/git_basics
  - title: Advanced Command Line Topics # NIK
    url: Advanced_CLI/advanced-command-line
  - title: Advanced Challenge Solutions # NIK
    url: Advanced_CLI/advanced-challenge-solutions
  #- title: Folder and Experiment Structure # MATT
  #  url:
  - title: Using Screen to Manage Multiple Projects (optional)
    url: Advanced_CLI/screen


  - heading: Intro to R
  - title: Introduction to R
    url: Intro_to_R/Intro2R/Intro2R_main
#  - title: Data in R - Prepare
#    url: Intro_to_R/Intro2R/data_in_R_prepare_fixed
#  - title: Data in R
#    url: Intro_to_R/Intro2R/data_in_R_fixed
  - title: Intro to tidyverse and ggplot2 - Prepare
    url: Intro_to_R/Intro2R/Intro_to_tidyverse_and_ggplot2_prepare
  - title: Intro to tidyverse and ggplot2
    url: Intro_to_R/Intro2R/Intro_to_tidyverse_and_ggplot2
  - title: Linear models in R
    url: Advanced_R/linear_models

  - heading: Spreadsheets
  - title: Working with spreadsheets
    url: spreadsheets/spreadsheets

  #- heading: Advanced R
  #- title: R Oddities
  #  url: Advanced_R/R_Oddities.Rmd
  #- title: Walkthrough of Vignettes for limma and biomaRt
  #  url: Advanced_R/limma_biomart_vignettes.Rmd
  #- title: Linear Models in R
  #  url: Advanced_R/linear_models.Rmd

  - heading: Bioinformatics
  - title: A Simple Bioinformatics Workflow
    url: Advanced_CLI/Bioinformatics_CLI

    # todo for Wed/Advanced_R:
      # stats talk = linear models in R?
      # R md  and notebooks
      # Data munging?
      # tidyverse, data frame manipulation
      # Figures in R and model building

  - heading: Support
  - title: Cheat Sheets
    url: cheatSheetIndex
  - title: Software and Links
    url: software
  - title: Scripts
    url: scripts/scripts_links

  - heading: ETC
  - title: Closing thoughts
    url: closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github
    url: https://github.com/ucdavis-bioinformatics-training/2019-Winter-Bioinformatics_Command_Line_and_R_Prerequisites_Workshop
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
